site_name: dychf # 项目名称
site_author: dychf # 作者


# 版权信息
copyright: Copyright &copy; 2023 — now |   dychf
# 配置
theme:
  name: material # 主题名称，Material已经是最优秀的选择了，相信我。
  language: en # 默认语言
  features: # 功能  
    - announce.dismiss # 可以叉掉公告的功能
    - content.action.edit # 编辑按钮，似乎没啥用
    - content.action.view # 查看按钮，似乎没啥用
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    - content.code.select # 选择代码按钮
    - content.tabs.link # 链接标签
    - content.tooltips # 不太清楚呢这个
    - header.autohide # 自动隐藏header
    - navigation.expand # 默认展开导航栏
    # - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    - navigation.prune # 只构建可见的页面
    - navigation.sections # 导航栏的section
    # - navigation.tabs # 顶级索引被作为tab
    # - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中
  palette:
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono
  language: zh # 一些提示性的文字会变成中文
  icon: # 一些用到的icon
    repo: fontawesome/brands/github
    # logo: fontawesome/solid/microchip
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code


# edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/dychf/dychf.github.io # 右上角点击跳转的链接
repo_name: dychf.github.io # 右上角的名字

extra:
  generator: False
  social:
    # - icon: fontawesome/brands/github
      # link: https://github.com/dychf
