
name: 推送部署
on:
  workflow_dispatch:
  push:
    branches: [ master ]  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy
        run: |
          # git checkout gh-pages
          # git pull
          mkdocs gh-deploy
  
